#!/usr/bin/env python
# -*- coding: utf-8 -*-
#

# This file is generated by pgr-generator please do not modify it !!!

from pgr import core 

class IExampleService:
    " Python interface of pl.simpatico.pgrexample.client.services.ExampleService Service interface "
    
    __serialization__ = {
         "sumInts": core.Types.INT,
         "subArray": core.Types.getArrayType(core.Types.STRING),
         "subObject": "pl.simpatico.pgrexample.client.vo.ExampleVo3",
         "loginUser": core.Types.BOOLEAN,
         "logout": core.Types.BOOLEAN
    }
    
    def sumInts(self, a, b):
        raise Exception("Please overwrite sum method in  ExampleService class")
    
    def subArray(self, tab, fr, to):
        raise Exception("Please overwrite subArray method in  ExampleService class")
    
    def subObject(self, src):
        raise Exception("Please overwrite subObject method in  ExampleService class")

    def loginUser(self, userName, password):
        raise Exception("Please overwrite subObject method in  ExampleService class")
    
    def logout(self):
        raise Exception("Please overwrite subObject method in  ExampleService class")
    