# First version of this file is generated by pgr-generator.

from pl.simpatico.pgrexample.client import iservices
from pgr import auth

class ExampleService(iservices.IExampleService):
    
    __perm__ = {
        "subArray" : ["user", "mgr","adm"],
        "subObject" : ["adm"],        
    }
    
    def sumInts(self, a, b):
        print a, b
        return a + b
    
    def subArray(self, tab, fr, to):
        return tab[fr:to]
    
    def subObject(self, src):
        res = src.objField
        res.strField = src.strField
        res.intField = src.intField
        return res
    
    def loginUser(self, userName, password):
        if userName == "user" and password == "pass":
            return auth.AuthorizationInterceptor.userAuthenticated("user", None)
        if userName == "mgr" and password == "pass":
            return auth.AuthorizationInterceptor.userAuthenticated("mgr", None)
        if userName == "adm" and password == "pass":
            return auth.AuthorizationInterceptor.userAuthenticated("adm", None)
        return False
    
    def logout(self):
        return auth.AuthorizationInterceptor.userDeauthenticated()
        
