

# This file is generated by pgr-generator please do not modify it !!!

__signatures__ = {
  'com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException':'3936916533', 'java.lang.String':'2004016611', '[Ljava.lang.String;':'2600011424', 'pl.simpatico.pgrexample.client.vo.ExampleVo2':'1675329647', 'pl.simpatico.pgrexample.client.vo.ExampleVo3':'58486052'
}